import type { HelpChatbotIntent } from "./help-chatbot.types";

export const HELP_CHATBOT_CONFIDENCE_THRESHOLD = 3;

export const helpChatbotIntents: HelpChatbotIntent[] = [
  {
    id: "registration_how_to",
    title: "Cómo registrarse",
    chips: ["Inscripción", "¿Cómo me registro?"],
    keywords: [
      "registro",
      "me registro",
      "como me registro",
      "registrarme",
      "registrar",
      "registrarse",
      "inscripcion",
      "me inscribo",
      "como me inscribo",
      "inscribo",
      "inscribirme",
      "inscribir",
      "inscribirse",
      "anotarme",
      "me anoto",
      "como me anoto",
      "anoto",
      "anotar",
      "participante",
    ],
    response:
      "Para inscribirte, completá el formulario de participantes con tus datos personales, seleccioná la modalidad de pago y subí el comprobante de transferencia.",
    links: [{ label: "Ir a inscripción", href: "/inscripcion/participantes" }],
    relatedIntentIds: ["registration_prices", "payment_receipt_upload"],
  },
  {
    id: "registration_prices",
    title: "Precios de inscripción",
    chips: ["Precios", "¿Cuánto cuesta?"],
    keywords: [
      "precio",
      "precios",
      "cuanto cuesta",
      "cuanto sale",
      "valor",
      "valores",
      "costo",
      "costos",
      "arancel",
      "pagar",
      "monto",
      "que sale",
    ],
    response:
      "Los precios visibles actuales son: 1 día $15.000, 3 días $40.000 y 3 días con alojamiento $70.000. Los valores finales se muestran en el formulario al elegir la modalidad.",
    links: [
      { label: "Ver opciones y precios", href: "/inscripcion/participantes" },
    ],
    relatedIntentIds: ["lodging_options", "registration_how_to"],
  },
  {
    id: "lodging_options",
    title: "Opciones con alojamiento",
    chips: ["Alojamiento", "Hay alojamiento?"],
    keywords: [
      "alojamiento",
      "alojar",
      "hotel",
      "hoteles",
      "dormis",
      "dormitorios",
      "hospedaje",
      "hospedar",
      "ubicacion",
      "transporte",
      "ciudad",
      "dónde es",
      "cómo llegar",
      "ubicación",
    ],
    response:
      "Podés revisar la página de ubicación y alojamiento para ver hoteles, transporte y datos de la ciudad. La opción 3 días con alojamiento incluye acceso completo y alojamiento.",
    links: [
      {
        label: "Inscripción con alojamiento",
        href: "/inscripcion/participantes",
      },
      {
        label: "Ver ubicación y alojamiento",
        href: "/ubicacion-y-alojamiento",
      },
    ],
    relatedIntentIds: ["registration_prices"],
  },
  {
    id: "payment_receipt_upload",
    title: "Enviar comprobante",
    chips: ["Comprobante", "¿Cómo envío el comprobante?"],
    keywords: [
      "comprobante",
      "recibo",
      "transferencia",
      "transferir",
      "pago",
      "pagar",
      "subir comprobante",
      "enviar comprobante",
      "adjuntar",
      "archivo",
      "imagen",
    ],
    negativeKeywords: [
      "segunda cuota",
      "cuota 2",
      "stand",
      "publicidad",
      "comercial",
    ],
    response:
      "El pago se realiza por transferencia fuera de la web. En el formulario, al final del proceso, subí una imagen del comprobante para que el comité lo revise.",
    links: [{ label: "Ir al formulario", href: "/inscripcion/participantes" }],
    relatedIntentIds: ["after_registration", "registration_how_to"],
  },
  {
    id: "after_registration",
    title: "Después de registrarse",
    chips: ["Después de registrarme"],
    keywords: [
      "despues de registrarme",
      "despues de inscribirme",
      "que pasa despues",
      "codigo de seguimiento",
      "seguimiento",
      "enviada",
      "pendiente",
      "revision",
      "revisar",
      "ya mande",
      "ya envie",
    ],
    response:
      "Cuando enviás la inscripción, recibís un código de seguimiento. La inscripción queda pendiente de revisión manual por el comité organizador.",
    // links: [{ label: "Ir a inscripción", href: "/inscripcion/participantes" }],
    relatedIntentIds: ["registration_confirmation", "second_installment"],
  },
  {
    id: "registration_confirmation",
    title: "Confirmación de inscripción",
    chips: ["Confirmación"],
    keywords: [
      "confirmacion",
      "confirmar",
      "cuando llega",
      "aprobacion",
      "aprobado",
      "aprobada",
      "email",
      "correo",
      "revision manual",
      "estado",
    ],
    response:
      "La confirmación no es automática: el comité revisa manualmente el comprobante. Si necesitás consultar tu caso, contactá al comité organizador.",
    links: [
      { label: "Contactar al comité", href: "/contacto" },
      {
        label: "Enviar email",
        href: "mailto:congresonacionalrcp@gmail.com",
        external: true,
      },
    ],
    relatedIntentIds: ["after_registration", "payment_receipt_rejected"],
  },
  {
    id: "second_installment",
    title: "Enviar segunda cuota",
    chips: ["Segunda cuota", "Enviar cuota 2"],
    keywords: [
      "segunda cuota",
      "cuota 2",
      "dos cuotas",
      "2 cuotas",
      "segundo pago",
      "pagar cuota",
      "enviar segunda",
      "cargar segunda",
      "informar segunda",
    ],
    negativeKeywords: ["stand", "publicidad", "comercial", "empresa"],
    response:
      "Si elegiste pagar en 2 cuotas y ya pagaste la primera, usá la página de segunda cuota. Vas a necesitar el código de seguimiento y el comprobante de la cuota 2.",
    links: [
      { label: "Informar segunda cuota", href: "/inscripcion/segunda-cuota" },
    ],
    relatedIntentIds: ["tracking_code_recovery"],
  },
  {
    id: "tracking_code_recovery",
    title: "Recuperar código de seguimiento",
    chips: ["No tengo mi código"],
    keywords: [
      "no tengo codigo",
      "perdi codigo",
      "recuperar codigo",
      "codigo seguimiento",
      "codigo de seguimiento",
      "no encuentro codigo",
      "tracking",
    ],
    response:
      "En la página de segunda cuota podés usar la opción No tengo mi código e ingresar el email usado al inscribirte.",
    links: [{ label: "Recuperar código", href: "/inscripcion/segunda-cuota" }],
    relatedIntentIds: ["second_installment"],
  },
  {
    id: "program",
    title: "Ver programa",
    chips: ["Programa", "¿Dónde veo el programa?"],
    keywords: [
      "programa",
      "agenda",
      "cronograma",
      "horarios",
      "actividades",
      "charlas",
      "talleres",
    ],
    response:
      "El programa del congreso está disponible en la sección Programa.",
    links: [{ label: "Ver programa", href: "/programa" }],
    relatedIntentIds: ["speakers"],
  },
  {
    id: "speakers",
    title: "Ver expositores",
    chips: ["Expositores", "¿Quiénes exponen?"],
    keywords: [
      "expositores",
      "expositor",
      "exponen",
      "exponentes",
      "ponentes",
      "disertantes",
      "disertante",
      "oradores",
      "speakers",
      "quienes hablan",
      "quien expone",
    ],
    response: "Podés ver los expositores en la sección Expositores.",
    links: [{ label: "Ver expositores", href: "/expositores" }],
    relatedIntentIds: ["program"],
  },
  {
    id: "stand_purchase",
    title: "Comprar un stand",
    chips: ["Comprar stand", "Stands"],
    keywords: [
      "stand",
      "stands",
      "comprar stand",
      "contratar stand",
      "expositor comercial",
      "espacio comercial",
      "empresa",
      "marca",
      "3x3",
    ],
    response:
      "Para contratar un stand, hace click en Comprar stand y completá el formulario.",
    links: [
      { label: "Comprar stand", href: "/inscripcion/expositores" },
      // { label: "Ver accesos comerciales", href: "/patrocinadores" },
    ],
    relatedIntentIds: ["commercial_second_installment", "contact_committee"],
  },
  {
    id: "advertising_purchase",
    title: "Contratar publicidad",
    chips: ["Publicidad", "Contratar publicidad"],
    keywords: [
      "publicidad",
      "publicitar",
      "auspiciar",
      "auspiciante",
      "patrocinador",
      "patrocinar",
      "patrocinio",
      "banner",
      "pantalla",
      "marca",
      "contratar publicidad",
    ],
    response:
      "Para contratar publicidad, elegí una opción publicitaria, completá los datos de la empresa y subí el comprobante para revisión.",
    links: [
      { label: "Contratar publicidad", href: "/inscripcion/publicidad" },
      // { label: "Ver accesos comerciales", href: "/patrocinadores" },
    ],
    relatedIntentIds: ["commercial_second_installment", "contact_committee"],
  },
  {
    id: "commercial_second_installment",
    title: "Segunda cuota comercial",
    chips: ["Cuota comercial"],
    keywords: [
      "segunda cuota comercial",
      "como pago la segunda cuota de mi stand",
      "pago la segunda cuota de mi stand",
      "pagar segunda cuota stand",
      "pago segunda cuota stand",
      "segunda cuota de mi stand",
      "segunda cuota del stand",
      "como pago la segunda cuota de publicidad",
      "pagar segunda cuota publicidad",
      "pago segunda cuota publicidad",
      "segunda cuota de publicidad",
      "cuota stand",
      "cuota publicidad",
      "segunda cuota stand",
      "segunda cuota publicidad",
      "stand segunda",
      "publicidad segunda",
      "comercial segunda",
    ],
    response:
      "Para informar la segunda cuota de un stand o publicidad, usá la página de segunda cuota comercial con tu código de seguimiento.",
    links: [
      {
        label: "Informar segunda cuota de Stand o Publicidad",
        href: "/inscripcion/comercial/segunda-cuota",
      },
    ],
    relatedIntentIds: ["stand_purchase", "advertising_purchase"],
  },
  {
    id: "contact_committee",
    title: "Contactar al comité",
    chips: ["Contacto", "Hablar con el comité"],
    keywords: [
      "contacto",
      "contactar",
      "comite",
      "organizador",
      "telefono",
      "whatsapp",
      "mail",
      "email",
      "consulta",
      "ayuda",
      "hablar",
    ],
    response:
      "Podés contactar al comité por la página de contacto, por email a congresonacionalrcp@gmail.com o por WhatsApp al 2392-460227.",
    links: [
      { label: "Ir a contacto", href: "/contacto" },
      {
        label: "Enviar email",
        href: "mailto:congresonacionalrcp@gmail.com",
        external: true,
      },
      {
        label: "Abrir WhatsApp",
        href: "https://wa.me/542392460227",
        external: true,
      },
    ],
  },
  {
    id: "discount_coupon_missing",
    title: "Cupón de descuento no recibido",
    chips: ["No llega el cupón"],
    keywords: [
      "cupon no llega",
      "no llego cupon",
      "no recibi cupon",
      "descuento no llega",
      "spam",
      "promociones",
      "correo descuento",
      "mail descuento",
    ],
    response:
      "Si solicitaste un cupón y no llega, revisá spam o promociones y verificá que usaste el email correspondiente. Si sigue sin llegar, contactá al comité.",
    links: [
      { label: "Solicitar cupón", href: "/inscripcion/participantes" },
      { label: "Contactar al comité", href: "/contacto" },
    ],
    relatedIntentIds: ["first_congress_discount"],
  },
  {
    id: "first_congress_discount",
    title: "Descuento primer congreso",
    chips: ["Descuento primer congreso"],
    keywords: [
      "descuento primer congreso",
      "participantes primer congreso",
      "primer congreso",
      "aplicar descuento",
      "beneficio exclusivo",
      "solicitar cupon",
      "cupon descuento",
      "codigo recibido",
    ],
    response:
      "En el formulario de participantes hay una sección de beneficio exclusivo. Solicitá el cupón con el mismo email usado en el primer congreso, luego pegá el código recibido y presioná Aplicar descuento.",
    links: [{ label: "Aplicar descuento", href: "/inscripcion/participantes" }],
    relatedIntentIds: ["discount_coupon_missing"],
  },
  {
    id: "wrong_data",
    title: "Datos cargados incorrectos",
    chips: ["Me equivoqué en mis datos"],
    keywords: [
      "me equivoque",
      "datos mal",
      "dato incorrecto",
      "modificar datos",
      "cambiar datos",
      "dni mal",
      "email mal",
      "corregir",
      "error datos",
    ],
    response:
      "Si ya enviaste la inscripción y te equivocaste en algún dato, contactá al comité indicando tu nombre, email y código de seguimiento.",
    links: [{ label: "Contactar al comité", href: "/contacto" }],
    relatedIntentIds: ["tracking_code_recovery"],
  },
  {
    id: "payment_receipt_rejected",
    title: "Comprobante rechazado",
    chips: ["Comprobante rechazado"],
    keywords: [
      "comprobante rechazado",
      "rechazado",
      "rechazada",
      "rechazo",
      "motivo rechazo",
      "pago rechazado",
      "recibo rechazado",
      "volver a enviar",
    ],
    response:
      "Si tu comprobante es rechazado, revisá el motivo informado y comunicate con el comité para saber cómo reenviar la información correcta.",
    links: [{ label: "Contactar al comité", href: "/contacto" }],
    relatedIntentIds: ["payment_receipt_upload"],
  },
];

export const helpChatbotFallbackIntentIds = [
  "registration_how_to",
  "second_installment",
  "program",
  "contact_committee",
] as const;
